export enum LocalStorageIdEnum {
    IS_DARKMODE_ENABLED = "IS_DARKMODE_ENABLED",
    IS_EMAIL_VERIFIED = "IS_EMAIL_VERIFIED",
    USER_DETAILS = "USER_DETAILS",
    IS_DISCLAIMER_OPEN = "IS_DISCLAIMER_OPEN",
    IS_EARLYFAN_BANNER_OPEN = "IS_EARLYFAN_BANNER_OPEN",
    IS_PWA_FIRST_TIME = "IS_PWA_FIRST_TIME",
    IS_FEEDBACK_GIVEN = "IS_FEEDBACK_GIVEN",
    COOKIE_DATA = "COOKIE_DATA",
    RELEASE_NOTES_VERSION = "RELEASE_NOTES_VERSION",
  }